server:
  port: 8001
spring:
  application:
    name: mall-admin
  profiles:
    active: dev #默认为开发环境
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      # 1 代表已删除，不配置默认是1，也可修改配置
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0，也可修改配置
      logic-not-delete-value: 0
      # 全局逻辑删除字段值
      logic-delete-field: deleteFlag
  mapper-locations: classpath:mapper/*.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头