spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: root
minio:
  # 文件地址
  endpoint: http://192.168.146.110:9000
  # key
  accessKey: 7ET58ISWWL78V1HBYN3W
  # 密钥
  secretKey: toKbaAYr+Pj6FWHu61+KUe2bt8jdX6fDq+53m3Mt
  # 桶名字
  bucketName: images
  # 最大上传文件
  maxSize: 20485760
  # 图片大小限制
  imagesMaxSize: 10485760